### PR TITLE
My requirement fix

### PR DESCRIPTION
**Pull request by Ohior**
removed tkinter because it comes by default with python and  and removed the default version of pillow

code-snapshot

### CODE REVIEW

**Comment by aydinnyunus** [comment]
I don't understand the reason for removing Tkinter and Pillow version

**Comment by Ohior** [comment]
> I don't understand the reason for removing Tkinter and Pillow version

There is an error when you pip installing with the requirement. This is because tkinter is already a python module and you cant pip install it.
The pillow version specified in the requirement also generate an error, I do not know which version you will like to use, that is why I did not add any version so that pip auto install the latest version

**Comment by aydinnyunus** [comment]
Thanks for your advice.

**Comment by Ohior** [comment]
🙂 no problem

**Pull request merged**
